example_1:
	gcc -g -o example_1 example_1.c

example_2:
	gcc -g -o example_2 example_2.c

example_3:
	gcc -g -o example_3 example_3.c

all:
	gcc -g -o example_1 example_1.c
	gcc -g -o example_2 example_2.c
	gcc -g -o example_3 example_3.c
	gcc -g -static -o example_4 example_4.c
